import { describe, expect, it } from 'vitest';
import { ProjectState } from '@arkiv/shared';
import { canTransition, NEXT } from './projects';

/**
 * §35 creative project state machine, as an exhaustive edge table: every (from, to) pair not listed here must
 * be refused. Written independently of NEXT so a widened map fails this test.
 */
const ALLOWED = `
PRODUCT_UPLOADED>PRODUCT_ANALYZED PRODUCT_UPLOADED>NEEDS_USER_ACTION PRODUCT_UPLOADED>BLOCKED_COMPLIANCE PRODUCT_UPLOADED>CANCELLED
PRODUCT_ANALYZED>BRIEF_READY PRODUCT_ANALYZED>NEEDS_USER_ACTION PRODUCT_ANALYZED>BLOCKED_COMPLIANCE PRODUCT_ANALYZED>CANCELLED
BRIEF_READY>CONCEPTS_READY BRIEF_READY>NEEDS_USER_ACTION BRIEF_READY>BLOCKED_COMPLIANCE BRIEF_READY>CANCELLED
CONCEPTS_READY>CONCEPT_SELECTED CONCEPTS_READY>NEEDS_USER_ACTION CONCEPTS_READY>BLOCKED_COMPLIANCE CONCEPTS_READY>CANCELLED
CONCEPT_SELECTED>STORYBOARD_READY CONCEPT_SELECTED>CONCEPTS_READY CONCEPT_SELECTED>NEEDS_USER_ACTION CONCEPT_SELECTED>BLOCKED_COMPLIANCE CONCEPT_SELECTED>CANCELLED
STORYBOARD_READY>STORYBOARD_APPROVED STORYBOARD_READY>CONCEPT_SELECTED STORYBOARD_READY>CONCEPTS_READY STORYBOARD_READY>NEEDS_USER_ACTION STORYBOARD_READY>BLOCKED_COMPLIANCE STORYBOARD_READY>CANCELLED STORYBOARD_READY>REFUNDED
STORYBOARD_APPROVED>RENDER_RESERVED STORYBOARD_APPROVED>BLOCKED_COMPLIANCE STORYBOARD_APPROVED>CANCELLED STORYBOARD_APPROVED>NEEDS_USER_ACTION STORYBOARD_APPROVED>PROVIDER_FAILED STORYBOARD_APPROVED>REFUNDED
RENDER_RESERVED>RENDERING RENDER_RESERVED>BLOCKED_COMPLIANCE RENDER_RESERVED>CANCELLED RENDER_RESERVED>NEEDS_USER_ACTION RENDER_RESERVED>PROVIDER_FAILED RENDER_RESERVED>REFUNDED
RENDERING>QA_RUNNING RENDERING>BLOCKED_COMPLIANCE RENDERING>NEEDS_USER_ACTION RENDERING>PROVIDER_FAILED RENDERING>REFUNDED RENDERING>CANCELLED
QA_RUNNING>COMPOSING QA_RUNNING>BLOCKED_COMPLIANCE QA_RUNNING>NEEDS_USER_ACTION QA_RUNNING>PROVIDER_FAILED QA_RUNNING>REFUNDED QA_RUNNING>CANCELLED
COMPOSING>PLATFORM_VARIANTS COMPOSING>NEEDS_USER_ACTION COMPOSING>PROVIDER_FAILED COMPOSING>REFUNDED COMPOSING>CANCELLED
PLATFORM_VARIANTS>FINAL_QA PLATFORM_VARIANTS>BLOCKED_COMPLIANCE PLATFORM_VARIANTS>NEEDS_USER_ACTION PLATFORM_VARIANTS>PROVIDER_FAILED PLATFORM_VARIANTS>REFUNDED PLATFORM_VARIANTS>CANCELLED
FINAL_QA>COMPLETE FINAL_QA>NEEDS_USER_ACTION FINAL_QA>PROVIDER_FAILED FINAL_QA>REFUNDED FINAL_QA>CANCELLED
NEEDS_USER_ACTION>PRODUCT_ANALYZED NEEDS_USER_ACTION>STORYBOARD_APPROVED NEEDS_USER_ACTION>RENDER_RESERVED NEEDS_USER_ACTION>RENDERING
NEEDS_USER_ACTION>PRODUCT_UPLOADED NEEDS_USER_ACTION>PROVIDER_FAILED NEEDS_USER_ACTION>BLOCKED_COMPLIANCE NEEDS_USER_ACTION>CANCELLED NEEDS_USER_ACTION>REFUNDED
BLOCKED_COMPLIANCE>STORYBOARD_READY BLOCKED_COMPLIANCE>CANCELLED BLOCKED_COMPLIANCE>REFUNDED
PROVIDER_FAILED>STORYBOARD_APPROVED PROVIDER_FAILED>REFUNDED PROVIDER_FAILED>CANCELLED
`
  .trim()
  .split(/\s+/);

describe('project state machine (§35)', () => {
  it('allows exactly the listed edges (exhaustive over all state pairs)', () => {
    const allowed = new Set(ALLOWED);
    const wrong: string[] = [];
    for (const from of ProjectState) {
      for (const to of ProjectState) {
        if (from === to) continue;
        const expected = allowed.has(`${from}>${to}`);
        if (canTransition(from, to) !== expected) wrong.push(`${from}>${to} expected ${expected ? 'allowed' : 'forbidden'}`);
      }
    }
    expect(wrong).toEqual([]);
    expect(Object.keys(NEXT).sort()).toEqual([...ProjectState].sort());
  });

  it('never skips approval, the reservation or QA', () => {
    expect(canTransition('PRODUCT_UPLOADED', 'COMPLETE')).toBe(false);
    expect(canTransition('STORYBOARD_READY', 'RENDERING')).toBe(false);
    expect(canTransition('STORYBOARD_READY', 'RENDER_RESERVED')).toBe(false);
    expect(canTransition('STORYBOARD_APPROVED', 'RENDERING')).toBe(false);
    expect(canTransition('RENDERING', 'COMPLETE')).toBe(false);
    expect(canTransition('PROVIDER_FAILED', 'COMPLETE')).toBe(false);
    expect(canTransition('NEEDS_USER_ACTION', 'COMPLETE')).toBe(false);
  });

  it('keeps terminal states terminal and never rewinds after approval', () => {
    for (const t of ['COMPLETE', 'REFUNDED', 'CANCELLED'] as const) for (const to of ProjectState) if (to !== t) expect(canTransition(t, to), `${t}>${to}`).toBe(false);
    expect(canTransition('RENDERING', 'STORYBOARD_READY')).toBe(false);
    expect(canTransition('STORYBOARD_APPROVED', 'CONCEPT_SELECTED')).toBe(false);
    expect(canTransition('CONCEPT_SELECTED', 'CONCEPTS_READY')).toBe(true);
  });
});
